development:
  home_auto:
    dimmers:
      - id: 'room_0'
        name: 'Living room'
      - id: 'room_1'
        name: 'Kitchen'
    switches:
      - id: 'living_room_light'
        name: 'Living Room Light'
        pin_num: 17
      - id: 'dinner_room_light'
        name: 'Dinner Room Light'
        pin_num: 4
test:
  home_auto:
    dimmers:
      - id: 'test_room_0'
        name: 'Living room (test)'
      - id: 'test_room_1'
        name: 'Kitchen (test)'
    switches:
      - id: 'test_room_1'
        name: 'Master room (test)'
        pin_num: 22
      - id: 'test_room_2'
        name: 'Kids room (test)'
        pin_num: 23
production:
